#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_TYPE_DELAY 10
#define MAX_DEFERRED_EXECUTORS 10
#define PERMISSIVE_HOLD
#define USB_SUSPEND_WAKEUP_DELAY 200
